const d = new Date("2021-03-21");
document.getElementById('a').innerHTML = d.getFullYear();
const B = new Date("2021-03-21");
document.getElementById('b').innerHTML = B.getMonth() +1 ;
const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
let K = new Date();
let mont = months[K.getMonth()]
document.getElementById('k').innerHTML = mont;
const C = new Date("2021-03-21");
document.getElementById('c').innerHTML = C.getDate();
const D = new Date(2021,2,14,16);
document.getElementById('d').innerHTML = D.getHours();
const E = new Date("2021-03-21");
document.getElementById('e').innerHTML = E.getMinutes();
const F = new Date("2021-03-21");
document.getElementById('f').innerHTML = F.getSeconds();
const G = new Date("2021-03-21");
document.getElementById('g').innerHTML = G.getMilliseconds();
const H = new Date("2021-03-24");
document.getElementById('h').innerHTML = H.getDay();
let days = ["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]
const J = new Date();
let da = days[J.getDay()]
document.getElementById('j').innerHTML = da;
const I = new Date("2021-03-24");
document.getElementById('i').innerHTML = I.getTime();
const date =  Date.now();
document.getElementById('l').innerHTML = date;
const minute = 1000*60;
const hour = 60 * minute
const day = hour * 24;
const year = day * 365;
let years = Math.round(Date.now()/year)
document.getElementById('m').innerHTML = years;
const R = new Date();
document.getElementById('n').innerHTML = R.getTimezoneOffset();
