let text = "john den";
document.getElementById("demo").innerHTML = text.length;
let text1 = "hello my name is \"rakesh\" and i am 26 years old";
document.getElementById('b').innerHTML = text1;
let text2 = "it\'s\ all right";
document.getElementById('c').innerHTML = text2;
let text3 = "i love music\\ i love to listining music."
document.getElementById('d').innerHTML = text3;
let text4 = 'good morning have a nice day.'
document.getElementById('g').innerHTML = "hello...." + 
text4 +" " +"thank you!!!";
let text5 = "be happy";
let text6 = new String("be happy");
document.getElementById('h').innerHTML = typeof text5 + " ,"+
typeof(text6);
let text7 = "dwegfuwfgeeyuolvnaioeurhwgvqutpsojnsc";
document.getElementById('k').innerHTML = text7.length;
let text8 = "hello gud morning have a nice day!!";
document.getElementById('l').innerHTML = text8.slice(3,11);
let text9 = "hello gud morning have a nice day!!";
document.getElementById('m').innerHTML = text9.slice(-12);//-12 to end
let text10 = "hellogudmorning haveaniceday!!";
document.getElementById('n').innerHTML = text10.slice(-10,-2);//-10 count ,-3 till 
let text11 = "hello gud morning have a nice day!!";
document.getElementById('o').innerHTML = text11.substring(10);
let text12 = "hello gud morning have a nice day!!";
document.getElementById('p').innerHTML = text12.substring(8,16);
let text13 = "hello gud morning have a nice day!!";
document.getElementById('r').innerHTML = text13.substr(8,4)
let text14 = "hello gud morning have a nice day!!";
document.getElementById('s').innerHTML = text14.substr(-5);
let text15 = "Please visit Microsoft and Microsoft!!";
document.getElementById('t').innerHTML = text15.replace('Microsoft','youtube');
document.getElementById('u').innerHTML = text15.replace(/MICROSOFT/i,'youtube');
document.getElementById('v').innerHTML = text15.replace(/Microsoft/g,'youtube');
let text16 = "I love cats. Cats are very easy to love. Cats are very popular."
text16 = text16.replaceAll('cats','dogs');
text16 = text16.replaceAll('Cats','Dogs');
document.getElementById('w').innerHTML = text16;
let text17 = "I love birds";
document.getElementById('x').innerHTML = text17.toUpperCase();
let text18 = "I love ANIMALS";
document.getElementById('y').innerHTML = text18.toLowerCase();
let text19 = "hello";
let text20 = "world!!";
document.getElementById('z').innerHTML = text19.concat(" ",text20); // in
let text21 = "     Hello world!!!      ";
let text22 = text21.trim();
document.getElementById('A').innerHTML ="the length of text21 without trim: "+ text21.length + ","+
"the length of the text22 with trim to remove white space: "+text22.length;
let text23 = "                 hello world.....  have a nice day                     ";
document.getElementById('B').innerHTML = text23.trimStart();
let text24 = "                           hello world !!!                ";
document.getElementById('C').innerHTML = text24.trimEnd();
let text25 = "7";
document.getElementById('D').innerHTML = text25.padStart(9,"x"); //in the 9th pace is put 7 other pace repace by x
let text26 = "7";
document.getElementById('E').innerHTML = text26.padEnd(9,"x");
let text27 = "Hello world!!";
document.getElementById('F').innerHTML = text27.charAt(0);
let text28 = "Hello world!!";
document.getElementById('G').innerHTML = text28.charCodeAt(0);
let text29 = "Hello world!!";
document.getElementById('H').innerHTML = text28[0];
let text30 = "Hello,world!!|GUD";
const text31 = text30.split(',');
const text32 = text30.split('|');
document.getElementById('I').innerHTML =text31[1];
document.getElementById('J').innerHTML =text32[1];
let text33 = "Hello";
const text34 = text33.split("");
document.getElementById('K').innerHTML =text34;